name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19 # or another version of your choice

    - name: Install dependencies
      run: npm install
      
    - name: Build the Docker image
      run: docker compose up --build 
